create table if not exists public.players (
  id bigint generated by default as identity primary key,
  external_id text null,
  name text not null,
  team text not null,
  position text null,
  nationality text null,
  age integer null,
  market_value bigint null,
  source_url text not null,
  scraped_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists players_external_id_unique
  on public.players (external_id)
  where external_id is not null;

create unique index if not exists players_name_team_unique
  on public.players (name, team);
