var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/onboarding/nombre/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1fac5d5c._.js")
R.c("server/chunks/ssr/_ec770f4e._.js")
R.c("server/chunks/ssr/_92d1eab0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e8b567f1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9703940e._.js")
R.c("server/chunks/ssr/f27f0_next_dist_386b210b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/f27f0_next_dist_client_components_builtin_global-error_0a804f8e.js")
R.c("server/chunks/ssr/[root-of-the-server]__8023723c._.js")
R.c("server/chunks/ssr/f27f0_next_dist_client_components_13e0da12._.js")
R.c("server/chunks/ssr/f27f0_next_dist_client_components_builtin_forbidden_f99297fa.js")
R.c("server/chunks/ssr/f27f0_next_dist_client_components_builtin_unauthorized_a42734e0.js")
R.c("server/chunks/ssr/app_onboarding_layout_tsx_ee9710ec._.js")
R.c("server/chunks/ssr/_next-internal_server_app_onboarding_nombre_page_actions_14c0e151.js")
R.m(5911)
module.exports=R.m(5911).exports
